BEGIN;

-- ================================
-- CLEANUP
-- ================================
DROP TABLE IF EXISTS public.review CASCADE;
DROP TABLE IF EXISTS public.inventory CASCADE;
DROP TABLE IF EXISTS public.classification CASCADE;
DROP TABLE IF EXISTS public.account CASCADE;
DROP TYPE IF EXISTS public.account_type;

-- ================================
-- ENUM
-- ================================
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

-- ================================
-- CLASSIFICATION
-- ================================
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    classification_name VARCHAR(30) NOT NULL UNIQUE
);

-- ================================
-- ACCOUNT
-- ================================
CREATE TABLE public.account (
    account_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_firstname VARCHAR(50) NOT NULL,
    account_lastname  VARCHAR(50) NOT NULL,
    account_email     VARCHAR(255) NOT NULL UNIQUE,
    account_password  VARCHAR(255) NOT NULL,
    account_type      account_type NOT NULL DEFAULT 'Client'
);

-- ================================
-- INVENTORY
-- ================================
CREATE TABLE public.inventory (
    inv_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inv_make        VARCHAR(50) NOT NULL,
    inv_model       VARCHAR(50) NOT NULL,
    inv_year        CHAR(4) NOT NULL CHECK (inv_year ~ '^[0-9]{4}$'),
    inv_description TEXT NOT NULL,
    inv_image       VARCHAR(255) NOT NULL,
    inv_thumbnail   VARCHAR(255) NOT NULL,
    inv_price       NUMERIC(9,0) NOT NULL CHECK (inv_price > 0),
    inv_miles       INT NOT NULL CHECK (inv_miles >= 0),
    inv_color       VARCHAR(30) NOT NULL,
    classification_id INT NOT NULL,
    CONSTRAINT fk_classification
        FOREIGN KEY (classification_id)
        REFERENCES public.classification(classification_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ================================
-- INDEXES (PERFORMANCE)
-- ================================
CREATE INDEX idx_inventory_classification
    ON public.inventory(classification_id);

CREATE INDEX idx_inventory_make_model
    ON public.inventory(inv_make, inv_model);

-- ================================
-- CLASSIFICATION DATA
-- ================================
INSERT INTO public.classification (classification_name) VALUES
('Custom'),
('Sport'),
('SUV'),
('Truck'),
('Sedan');

-- ================================
-- INVENTORY DATA (SAFE FK INSERT)
-- ================================
INSERT INTO public.inventory (
    inv_make, inv_model, inv_year, inv_description,
    inv_image, inv_thumbnail, inv_price, inv_miles,
    inv_color, classification_id
)
SELECT
    v.inv_make, v.inv_model, v.inv_year, v.inv_description,
    v.inv_image, v.inv_thumbnail, v.inv_price,
    v.inv_miles, v.inv_color, c.classification_id
FROM (
   VALUES
-- =======================
-- SEDAN
-- =======================
('Chevy','Camaro','2018',
 'If you want to look cool, this is the car you need. It offers great performance at an affordable price.',
 '/images/camaro.jpg','/images/camaro-tn.jpg',25000,101222,'Silver','Sedan'),

('Lamborghini','Adventador','2016',
 'This powerful V-12 sports car delivers extreme performance. Buckle up and enjoy the ride.',
 '/images/adventador.jpg','/images/adventador-tn.jpg',417650,71003,'Blue','Sedan'),

-- =======================
-- CUSTOM
-- =======================
('Batmobile','Custom','2007',
 'Ever want to be a superhero? Now you can. This iconic vehicle even features a motorcycle mode.',
 '/images/batmobile.jpg','/images/batmobile-tn.jpg',65000,29887,'Black','Custom'),

('FBI','Surveillance Van','2016',
 'Feel like you stepped into a crime drama. This van includes professional surveillance equipment.',
 '/images/survan.jpg','/images/survan-tn.jpg',20000,19851,'Brown','Custom'),

('Dog','Car','1997',
 'Straight from the 90s, this original Dog Car comes complete with fluffy ears and classic charm.',
 '/images/dog-car.jpg','/images/dog-car-tn.jpg',35000,71632,'White','Custom'),

('Aerocar International','Aerocar','1963',
 'Beat rush-hour traffic with this rare vehicle that converts into an airplane.',
 '/images/aerocar.jpg','/images/aerocar-tn.jpg',700000,18956,'Red','Custom'),

('Monster','Truck','1995',
 'Built for fun, not work. Massive tires make this truck perfect for mud and jumps.',
 '/images/monster-truck.jpg','/images/monster-truck-tn.jpg',150000,3998,'Purple','Custom'),

('Mystery','Machine','1999',
 'Trusted by Scooby and the gang, this iconic van is ready to solve mysteries.',
 '/images/mystery-van.jpg','/images/mystery-van-tn.jpg',10000,128564,'Green','Custom'),

-- =======================
-- SUV
-- =======================
('Jeep','Wrangler','2019',
 'Compact yet powerful, perfect for daily driving and serious off-road adventures.',
 '/images/wrangler.jpg','/images/wrangler-tn.jpg',28045,41205,'Yellow','SUV'),

-- =======================
-- TRUCK
-- =======================
('Cadillac','Escalade','2019',
 'Luxury and comfort combined for any occasion.',
 '/images/escalade.jpg','/images/escalade-tn.jpg',75195,41958,'Black','Truck'),

('GM','Hummer','2016',
 'Built for rugged terrain and extreme off-road challenges.',
 '/images/hummer.jpg','/images/hummer-tn.jpg',58800,56564,'Yellow','Truck'),

('Spartan','Fire Truck','2012',
 'Fully equipped fire truck featuring hose and water tank.',
 '/images/fire-truck.jpg','/images/fire-truck-tn.jpg',50000,38522,'Red','Truck'),

-- =======================
-- SPORT
-- =======================
('Mechanic','Special','1964',
 'This mystery vehicle needs TLC, but it has potential.',
 '/images/mechanic.jpg','/images/mechanic-tn.jpg',100,200125,'Rust','Sport'),

('Ford','Model T','1921',
 'The first mass-produced automobile in history.',
 '/images/model-t.jpg','/images/model-t-tn.jpg',30000,26357,'Black','Sport'),

('Ford','Crown Victoria','2013',
 'Former law enforcement vehicle now available to the public.',
 '/images/crwn-vic.jpg','/images/crwn-vic-tn.jpg',10000,108247,'White','Sport')

) AS v(
    inv_make, inv_model, inv_year, inv_description,
    inv_image, inv_thumbnail, inv_price,
    inv_miles, inv_color, classification_name
)
JOIN public.classification c
  ON c.classification_name = v.classification_name;

-- ================================
-- IMAGE PATH UPDATE
-- ================================
UPDATE public.inventory
SET
  inv_image     = REPLACE(inv_image, '/images/', '/images/vehicles/'),
  inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');

-- ================================
-- SAMPLE ACCOUNT
-- ================================
INSERT INTO public.account (
    account_firstname, account_lastname, account_email,
    account_password, account_type
)
VALUES (
    'John','Doe','john@example.com',
    '$2a$10$N7B3Z8s9cTqYwVhLmNpQReKjK8S2M3X4V5B6n7C8d9e0f1g2h3i4j5',
    'Client'
);

-- ================================
-- REVIEW
-- ================================
CREATE TABLE public.review (
    review_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_text TEXT NOT NULL,
    review_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    inv_id INT NOT NULL,
    account_id INT NOT NULL,
    CONSTRAINT fk_review_inventory
        FOREIGN KEY (inv_id)
        REFERENCES public.inventory(inv_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_review_account
        FOREIGN KEY (account_id)
        REFERENCES public.account(account_id)
        ON DELE
